// three-scope-map/assets/templates/smart-mine-vue/src/components/map/EarthChinaMap.vue
<!--
  SPDX-License-Identifier: GPL-3.0-or-later
  Copyright (c) 2026 宋夏天Dazzle
  作者全平台ID：宋夏天Dazzle；公众号：送你整个夏天
  Source: https://github.com/songsummer920-dazzle/three-scope-map-skill
-->

<template>
  <div ref="mount" class="earth-china-mount" />
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';
import {
  createEarthChinaMap,
  type EarthChinaMapHandle,
  type EarthChinaMapMode,
} from './core/earthChinaMapCore';

const emit = defineEmits<{ 'mode-change': [mode: EarthChinaMapMode] }>();

const mount = ref<HTMLElement>();
let instance: EarthChinaMapHandle | undefined;

onMounted(() => {
  if (!mount.value) return;
  instance = createEarthChinaMap(mount.value, {
    onModeChange: (mode) => emit('mode-change', mode),
  });
});

onBeforeUnmount(() => {
  instance?.destroy();
  instance = undefined;
});
</script>

// three-scope-map/assets/templates/smart-mine-react/src/components/map/EarthChinaMap.tsx
// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2026 宋夏天Dazzle
// 作者全平台ID：宋夏天Dazzle；公众号：送你整个夏天
// Source: https://github.com/songsummer920-dazzle/three-scope-map-skill
import { useEffect, useRef } from 'react';
import {
  createEarthChinaMap,
  type EarthChinaMapMode,
} from './core/earthChinaMapCore';

export type { EarthChinaMapMode };

export default function EarthChinaMap({
  onModeChange,
}: {
  onModeChange?: (mode: EarthChinaMapMode) => void;
}) {
  const mount = useRef<HTMLDivElement>(null);
  const onModeChangeRef = useRef(onModeChange);
  onModeChangeRef.current = onModeChange;

  useEffect(() => {
    if (!mount.current) return;
    const instance = createEarthChinaMap(mount.current, {
      onModeChange: (mode) => onModeChangeRef.current?.(mode),
    });
    return () => instance.destroy();
  }, []);

  return <div ref={mount} className="earth-china-mount" />;
}
